### ISSUE TITLE
Android builds don't compile with SDK version 20.4.8

### ISSUE THREAD

**Issue by JacquesLeupin** [Countly/countly-sdk-react-native-bridge#30]
See below for message thrown during build:

```
/Users/jackleupin/SerenityRN/node_modules/countly-sdk-react-native-bridge/android/src/main/java/ly/count/android/sdk/react/CountlyReactNative.java:893: error: no suitable method found for log(String)
        log("recordAttributionID: Not implemented for Android");
```

I think a fix might look something like this:

```
    @ReactMethod
    public void recordAttributionID(ReadableArray args, LogLevel logLevel){
        String attributionID = args.getString(0);
        log("recordAttributionID: Not implemented for Android", logLevel.DEBUG);
```
